fixtures:
  repositories:
    'keystone': 'git://github.com/openstack/puppet-keystone.git'
    'openstacklib': 'git://github.com/openstack/puppet-openstacklib.git'
    'stdlib': 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    'python': 'git://github.com/stankevich/puppet-python.git'
  symlinks:
    'monasca': "#{source_dir}"
